<?php
$this->headLink()->appendStylesheet($this->baseUrl().'/backend/css/custom/controlB.css')
	->appendStylesheet($this->baseUrl().'/backend/css/custom/dialog.css');
?>
<style>
	.widget { background: none; border: 0px; clear: both; margin-top: 10px;}
</style>
<div class="titleArea">
        <div class="wrapper">
            <div class="pageTitle">
				<br>
                <h5>Dashboard</h5>
            </div>
            <div class="clear"></div>
        </div>
    </div>
<div class="wrapper" >

<div class="widget">                                
           <div class="controlB">
			<ul>	
				<li>
					<a title="OCW" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'ocw', 'action'=>'index'))?>">
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/ocw.png">
						<span>OCW</span>
					</a>
				</li>
				<li>
					<a  title="Categories" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'category', 'action'=>'index'))?>">
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/category.png">
						<span>Categories</span>
					</a>
				</li>
				<li>
					<a title="Persons" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'person', 'action'=>'index'))?>">
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/female_male_users.png">
						<span>Persons</span>
					</a>
				</li>
				<li>
					<a title="Degrees" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'degree', 'action'=>'index'))?>">
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/degree.png">
						<span>Degrees</span>
					</a>
				</li>
				<li>
					<a title="Universities" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'university', 'action'=>'index'))?>" >
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/university.png">
						<span>Universities</span>
					</a>
				</li>
				<li>
					<a title="Testimonials" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'testimonial', 'action'=>'index'))?>" >
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/comments.png">
						<span>Testimonials</span>
					</a>
				</li>
				<li>
					<a title="Contact Requests" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'contact', 'action'=>'index'))?>" >
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/mail.png">
						<span>Contact Requests</span>
					</a>
				</li>
				<li>
					<a title="Edit Styles" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'stylefile', 'action'=>'index'))?>" >
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/styling.png">
						<span>Edit Styles</span>
					</a>
				</li>
				<li>
					<a title="Broken Links" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'blc', 'action'=>'index'))?>" >
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/Link-icon.png">
						<span>Broken Links</span>
					</a>
				</li>
				<li>
					<a title="Promotions" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'ads', 'action'=>'index'))?>" >
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/office_customer_male.png">
						<span>Promotions</span>
					</a>
				</li>
				<li>
					<a title="Frontend" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'frontend', 'action'=>'index'))?>" >
						<img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/frontend_manager_1.png">
						<span>FrontEnd</span>
					</a>
				</li>
			</ul>
		<div class="clear"></div>
		</div>
</div>
</div>