<div class="errorWrapper" style="margin-top:30px;">
    <span class="sadEmo"></span>
    <span class="errorTitle">Not authorized to access this section</span>
    <span class="errorNum">401</span>
    <span class="errorDesc">For more details contact the system administrator</span>
    <a href="<?php echo $this->url(array( 'controller'=>'index', 'action'=>'index'))?>" title="" class="button dredB"><img class="icon" alt="" src="<?php echo $this->baseUrl() ?>/backend/images/icons/light/home.png"><span>Back to the home</span></a>
</div>