<?php
$this->jQuery()->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/datatable.fnReloadAjax.js')
    ->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/TableTools/media/js/TableTools.js')
    ->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/TableTools/media/js/ZeroClipboard.js')
    ->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/advancedFilter.js')
    ->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/ui/jquery.prettyPhoto.js');

$this->headLink()->appendStylesheet($this->baseUrl().'/backend/js/plugins/tables/TableTools/media/css/TableTools.css')
    ->appendStylesheet($this->baseUrl().'/backend/js/plugins/tables/TableTools/media/css/TableTools_JUI.css');
?>

<div class="topHeader" style="top:0px;">
    <div class="titleArea">
        <div class="wrapper">
            <div class="TopPageTitle">
                <div class="bc">
                    <ul id="breadcrumbs" class="breadcrumbs">
                        <li><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'index', 'action'=>'index') )?>">Home</a></li>
                        <li><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'frontend', 'action'=>'index') )?>">Frontend Dashboard</a></li>
                        <li class="current"><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'ffooter', 'action'=>'index') )?>">Pages Design list</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div class="wrapper">
        <div id="mensajes"></div>
        <div id="breadcrumbs-wrapper" style="display: none;" >
            <div class="fbc">
                <ul id="fbreadcrumbs" class="fbreadcrumbs">
                </ul>
                <div class="clear"></div>
            </div>
        </div>
        <div class="dataTables_wrapper">
            <!-- Dynamic table -->
            <div class="widget">
                <div class="title">
                    <a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'ffooter', 'action'=>'editfooter') )?>"><img class="titleIcon" alt="" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/add.png"></a>

                    <a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'ffooter', 'action'=>'designfooter') )?>" alt="Design Footer"><img class="titleIcon" alt="Design Footer" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/paintBrushFoo.png"></a>

                    <a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'ffooter', 'action'=>'designheader') )?>"><img class="titleIcon" alt="Design Header" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/paintBrushHea.png"></a>

                    <div class="clear"></div>
                </div>
                <table class="display dTable">
                    <thead>
                    <tr>
                        <th>Functions</th>
                        <th>Area</th>
                        <th>Description</th>
                        <th>Order</th>
                        <th>Url</th>
                        <th>On footer</th>
                        <th>On header</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var oTable;
    $(document).ready(function() {

        $.jGrowl.defaults.closerTemplate = '<div>[close all]</div>';
        var calcDataTableHeight = function() {
            return $(window).height()-300 ;
        };

        oTable = $('.dTable').dataTable( {
            "bFilter": false,
            "bJQueryUI": true, // UI theme support
            "sPaginationType": "full_numbers", // show the page numbers
            "bRetrieve"  : true,
            "bProcessing": true,
            "bServerSide": true, // not necessary
            "aoColumns": [{ "sWidth": "70px", "bSortable": false }, { "sWidth": "auto" }, { "sWidth": "auto" }, { "sWidth": "auto" }, { "sWidth": "auto" }, { "sWidth": "auto" }, { "sWidth": "auto" }],
            "aaSorting":[[1,'asc']],
            "iDisplayLength": 50,
            "sScrollx": "100%",
            "sScrollY": calcDataTableHeight() ,
            "bScrollCollapse": true,
            "bSortClasses": true, // don't show the order classes
            "sAjaxSource": '<?php echo $this->url(array( 'controller'=>'ffooter', 'action'=>'footergrid'))?>',

            "fnServerParams": function ( aoData ) {
                var filters = getAdvancedFilters();
                aoData.push( { "name": "filters", "value": JSON.stringify(filters.filters) } );
            } ,

            "sServerMethod": "POST",
            "bDestroy": true,

            "oTableTools": {
                "sSwfPath": "<?php echo $this->baseUrl()?>/backend/js/plugins/tables/TableTools/media/swf/copy_csv_xls_pdf.swf"
            },

            "oTableTools": {
                "aButtons": []
            },

            "fnCreatedRow": function( nRow, aData, iDataIndex ) {

                // buttons
                var editar = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Edit" href="#"><img alt="" src="/backend/images/icons/color/pencil.png"></a>');
                var borrar = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Delete" href="#"><img alt="" src="/backend/images/icons/color/cross.png"></a>');
                editar.on('click',function(){
                    var form = $('<form>').attr({
                        name:'editform',
                        method: 'post',
                        action: '<?php echo $this->url(array('module'=>'admin','controller'=>'ffooter', 'action'=>'editfooter'))?>'
                    });
                    $('<input>').attr({
                        type: 'hidden',
                        id: 'id',
                        name: 'id',
                        value: aData[0]
                    }).appendTo(form);
                    form.appendTo($('body'));
                    form.submit();
                    return false;
                });
                borrar.on('click',function(){
                    $.msgbox("Are you sure you want to remove this text? <br> You cannot undo this action", {
                        type: "confirm",
                        buttons : [
                            {type: "submit", value: "Yes"},
                            {type: "cancel", value: "No"}
                        ]
                    }, function(result) {
                        if(result === 'Yes'){
                            var form = $('<form>').attr({
                                name:'deleteform',
                                method: 'post',
                                action: '<?php echo $this->url(array('module'=>'admin','controller'=>'ffooter', 'action'=>'delete'))?>'
                            });
                            $('<input>').attr({
                                type: 'hidden',
                                id: 'id',
                                name: 'id',
                                value: aData[0]
                            }).appendTo(form);
                            form.appendTo($('body'));
                            form.submit();
                            return false;
                        }
                    });
                });
                $('td:eq(0)', nRow).empty();
                $('td:eq(0)', nRow).append(editar);
                $('td:eq(0)', nRow).append(borrar);
            }
            ,"oLanguage": { "sUrl": "<?php echo $this->baseUrl()?>/backend/js/plugins/tables/en.txt"}
        });


        $(window).resize(function () {
            var oSettings = oTable.fnSettings();
            oSettings.oScroll.sY = calcDataTableHeight();
            oTable.fnDraw();
        });

    } );
</script>