<?php
$this->jQuery()->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/datatable.fnReloadAjax.js')
->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/TableTools/media/js/TableTools.js')
->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/TableTools/media/js/ZeroClipboard.js')
->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/advancedFilter.js')
;
$this->headLink()->appendStylesheet($this->baseUrl().'/backend/js/plugins/tables/TableTools/media/css/TableTools.css')
->appendStylesheet($this->baseUrl().'/backend/js/plugins/tables/TableTools/media/css/TableTools_JUI.css')
;
?>
<div class="topHeader" style="top:0px;">
	<div class="titleArea">
		<div class="wrapper">
			<div class="TopPageTitle"><div class="bc">
					<ul id="breadcrumbs" class="breadcrumbs">
						<li><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'index', 'action'=>'index') )?>">Home</a></li>						
						<li class="current"><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'person', 'action'=>'index') )?>">Person list</a></li>
					</ul>
				</div>				
			</div>			
		</div>
	</div>
</div>
<div id="content">
	<div class="wrapper">
	 	<div id="mensajes"></div>	
	 	<div class="filterDetailed" id="f1" style="display:none;">
			                    <div class="filterContent">
			                        <div class="advancedFilterButons">
			                        	<a class="button basic" title="" href="javascript:reloadFilters();" id="reload-table">
											<img class="icon" alt="" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/refresh2.png">
											<span title="Reload Filters">Reload</span>
										</a>
			                        	<a class="button basic"  title="" href="javascript:clarFilters();" id="clean-filters">
											<img class="icon" alt="" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/smallBrush.png">
											<span title="Clean filters">Clean</span>
										</a>		                            
			                        </div>
			                        <span class="line"></span>
			                        <div class="advancedFilterToggle">
										<div class="toggle acc">
						                    <div class="title"><img src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/list.png" alt="" class="titleIcon" /><h6>Name</h6></div>
						                    <div class="menu_body">
						                    	<form class="form" action="" id="" onsubmit="return false;">
						                    		<input type="hidden" name="type" value="TEXT" >
						                    		<input type="hidden" name="op" value="LIKE" >
						                    		<input type="hidden" name="label" value="Name" >
						                    		<div class="formRow">
														<label for="per_name">Name:</label>
														<div class="formRight">
															<input id="per_name" name="CONCAT( perFirstName, perLastName)" type="text" value="" >
														</div>
														<div class="clear"></div>
													</div>
												</form>	
						                    </div>
						                    <div class="title"><img src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/list.png" alt="" class="titleIcon" /><h6>City</h6></div>
						                    <div class="menu_body">
						                    	<form class="form" action="" id="" onsubmit="return false;">
						                    		<input type="hidden" name="type" value="TEXT" >
						                    		<input type="hidden" name="op" value="LIKE" >
						                    		<input type="hidden" name="label" value="City" >
						                    		<div class="formRow">
														<label for="perCity">City:</label>
														<div class="formRight">
															<input id="perCity" name="perCity" type="text" value="" >
														</div>
														<div class="clear"></div>
													</div>
												</form>	
						                    </div>
						                    <div class="title"><img src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/list.png" alt="" class="titleIcon" /><h6>State</h6></div>
						                    <div class="menu_body">
						                    	<form class="form" action="" id="" onsubmit="return false;">
						                    		<input type="hidden" name="type" value="TEXT" >
						                    		<input type="hidden" name="op" value="LIKE" >
						                    		<input type="hidden" name="label" value="State" >
						                    		<div class="formRow">
														<label for="perState">State:</label>
														<div class="formRight">
															<input id="perState" name="perState" type="text" value="" >
														</div>
														<div class="clear"></div>
													</div>
												</form>	
						                    </div>
						                    <div class="title"><img src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/list.png" alt="" class="titleIcon" /><h6>Country</h6></div>
						                    <div class="menu_body">
						                    	<form class="form" action="" id="" onsubmit="return false;">
						                    		<input type="hidden" name="type" value="TEXT" >
						                    		<input type="hidden" name="op" value="LIKE" >
						                    		<input type="hidden" name="label" value="Country" >
						                    		<div class="formRow">
														<label for="perCountry">Country:</label>
														<div class="formRight">
															<input id="perCountry" name="perCountry" type="text" value="" >
														</div>
														<div class="clear"></div>
													</div>
												</form>	
						                    </div>
						                </div>
			                        </div>
			                    </div>
		</div>	
			                	 	
	    <div class="dataTables_wrapper">
	        <!-- Dynamic table -->
	        <div class="widget">
	            <div class="title">
	            	<a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'person', 'action'=>'editperson') )?>"><img class="titleIcon" alt="" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/add.png"></a>
		            <a href="javascript:displayFilter()">
		            	<img style="margin-left: 243px;border:none;" class="titleIcon" alt="" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/filter.png">
		            </a>
		            <div id="breadcrumbs-wrapper" style="" >
				       <div class="fbc">
				            <ul id="fbreadcrumbs" class="fbreadcrumbs">
				            </ul>
				            <div class="clear"></div>    
				        </div> 
				    </div>
	            	<div class="clear"></div>
	            </div>                          
	            <table class="display dTable">
	                <thead>
	                    <tr>
							<th>Functions</th>
							<th>Name</th>
	                    	<th>E-Mail</th>
	                    	<th>Optional E-Mail</th>
	                    	<th>Personal url</th>
	                        <th>Phone</th>
	                        <th>City</th>
	                        <th>State</th>
	                        <th>Country</th>	                        
	                    </tr>
	                </thead>
	                <tbody>	                    
	                </tbody>
	            </table>
	        </div>  
	    </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	<?php if($this->success){ ?>
		$('#mensajes').message({ type: 'success',  frase: '<?php  echo $this->success ?>', prefrase: 'Success'  });
		setTimeout(function(){ $("#mensajes").fadeOut(800);$("#mensajes").html('');}, 3000);
	<?php }?>
	<?php if($this->error){ ?>
		$('#mensajes').message({ type: 'error',  frase: '<?php  echo $this->error ?>', prefrase: 'Error'  });
		setTimeout(function(){ $("#mensajes").fadeOut(800);$("#mensajes").html('');}, 3000);
	<?php }?>	
});
    var oTable;
    $(document).ready(function() {

    	$.jGrowl.defaults.closerTemplate = '<div>[close all]</div>';
    	var calcDataTableHeight = function() {
            return $(window).height()-300 ;
        };
    	oTable = $('.dTable').dataTable( { 
            "bJQueryUI": true, // UI themes support
            "sPaginationType": "full_numbers", // show the page numbers
            "bRetrieve"  : true,
            "bProcessing": true,
        	"bServerSide": true,
        	"sDom": '<""flT>rt<"F"ip>',
    		"aoColumns": [
    		              { "sWidth": "90px", "bSortable": false }, { "sWidth": "300px" },{ "sWidth": "200px" },{ "sWidth": "200px" },{ "sWidth": "295px" },{ "sWidth": "150px" },{ "sWidth": "150px" },{ "sWidth": "150px" },{ "sWidth": "150px" }
    		          ],
    		"aaSorting":[[1,'asc']],
        	"iDisplayLength": 50,
            "sScrollY": calcDataTableHeight() ,
            "sScrollX": "100%",
            "bScrollCollapse": true,
            "bSortClasses": false,
            "sAjaxSource": '<?php echo $this->url(array( 'controller'=>'person', 'action'=>'persongrid'))?>',

            "fnServerParams": function ( aoData ) {
                var filters = getAdvancedFilters();
                aoData.push( { "name": "filters", "value": JSON.stringify(filters.filters) } );
            } ,             
            
            "sServerMethod": "POST",
            "bDestroy": true,
            
            "oTableTools": {
                "sSwfPath": "<?php echo $this->baseUrl()?>/backend/js/plugins/tables/TableTools/media/swf/copy_csv_xls_pdf.swf"
            },
            "oTableTools": {
            	"aButtons": []
    		},
    		
            "fnCreatedRow": function( nRow, aData, iDataIndex ) {
                // buttons
               	var editar = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Edit" href="#"><img alt="" src="/backend/images/icons/color/pencil.png"></a>');
                var borrar = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Delete" href="#"><img alt="" src="/backend/images/icons/color/cross.png"></a>');
                editar.on('click',function(){
                   	 var form = $('<form>').attr({
                          name:'editform', 
                          method: 'post', 
                          action: '<?php echo $this->url(array('module'=>'admin','controller'=>'person', 'action'=>'editperson'))?>'
                      });
                      $('<input>').attr({
                           type: 'hidden',
                           id: 'id',
                           name: 'id',
                           value: aData[0]
                       }).appendTo(form);
                       form.appendTo($('body'));
                       form.submit();
                       return false;
                     });
                     borrar.on('click',function(){
                    		$.msgbox("Are you sure you want to remove this person? <br> You cannot undo this action", {
                    			  type: "confirm",
                    			  buttons : [
                    			    {type: "submit", value: "Yes"},
                    			    {type: "cancel", value: "No"}
                    			  ]
                    			}, function(result) {
                    				if(result === 'Yes'){
                                      	 var form = $('<form>').attr({
                                             name:'deleteform', 
                                             method: 'post', 
                                             action: '<?php echo $this->url(array('module'=>'admin','controller'=>'person', 'action'=>'delete'))?>'
                                         });
                                         $('<input>').attr({
                                             type: 'hidden',
                                             id: 'Id',
                                             name: 'Id',
                                             value: aData[0]
                                         }).appendTo(form);
                                         form.appendTo($('body'));
                                         form.submit();
                                         return false;
                    				}
                    			});
                     });                     
                     $('td:eq(0)', nRow).empty();
                     $('td:eq(0)', nRow).append(editar); 
                     $('td:eq(0)', nRow).append(borrar);                      
              }
            ,"oLanguage": { "sUrl": "<?php echo $this->baseUrl()?>/backend/js/plugins/tables/en.txt"}
        });
        

       $(window).resize(function () {
	        var oSettings = oTable.fnSettings();
	        oSettings.oScroll.sY = calcDataTableHeight(); 
	        oTable.fnDraw();
        }); 
		// draw the filters if they exists
		drawfbreadcrumbs(getAdvancedFilters()); 

    } );

    function reloadFilters(){
		oTable.fnReloadAjax( '<?php echo $this->url(array( 'module'=>'admin',  'controller'=>'person', 'action'=>'persongrid'))?>' );
		drawfbreadcrumbs(getAdvancedFilters()); 
	}
</script>