<?php
$this   ->jQuery()->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/datatable.fnReloadAjax.js')
        ->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/TableTools/media/js/TableTools.js')
        ->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/TableTools/media/js/ZeroClipboard.js')
        ->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/advancedFilter.js')
;
$this->headLink()->appendStylesheet($this->baseUrl().'/backend/js/plugins/tables/TableTools/media/css/TableTools.css')
    ->appendStylesheet($this->baseUrl().'/backend/js/plugins/tables/TableTools/media/css/TableTools_JUI.css')
;
?>

<div class="topHeader" style="top:0px;">
    <div class="titleArea">
        <div class="wrapper">
            <div class="TopPageTitle">
                <div class="bc">
                    <ul id="breadcrumbs" class="breadcrumbs">
                        <li><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'index', 'action'=>'index') )?>">Home</a></li>
                        <li class="current"><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'stylefile', 'action'=>'index') )?>">Style File list</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div class="wrapper">
        <div id="mensajes"></div>
        <div id="breadcrumbs-wrapper" style="display: none;" >
            <div class="fbc">
                <ul id="fbreadcrumbs" class="fbreadcrumbs">
                </ul>
                <div class="clear"></div>
            </div>
        </div>
        <div class="dataTables_wrapper">
            <!-- Dynamic table -->
            <div class="widget">
                <div class="title">
                    <div class="clear"></div>
                </div>
                <table class="display dTable">
                    <thead>
                    <tr>
                        <th>Functions</th>
                        <th>Description</th>
                        <th>Short Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="log-info-box" title="Log info" style="display: none;">
    <table id="tgrid"  class="display">
        <tr>
            <th>Action</th>
            <th>Style File</th>
            <th>Date</th>
            <th>User</th>
        </tr>
    </table>
</div>

<script type="text/javascript">
    var oTable;
    var unchange_bk = "<?php echo $this->changes ?>";

    $(document).ready(function() {

        if(unchange_bk.length > 0){
            $.msgbox(unchange_bk, {
                type: "confirm",
                buttons : [{type: "submit", value: "Ok"}]
            });
        }

        $( "#log-info-box" ).dialog({
            modal: true,
            autoOpen: false,
            width: 800,
            height: 500,
            resizable: false,
            buttons: {
                Ok: function() {
                    $( this ).dialog( "close" );
                }
            },
            close: function() {
                $( this ).dialog( "close" );
                $(".action").remove();
            }
        });

        $.jGrowl.defaults.closerTemplate = '<div>[close all]</div>';
        var calcDataTableHeight = function() {
            return $(window).height()-300 ;

        };
        oTable = $('.dTable').dataTable( {
            "bJQueryUI": true, // UI themes support
            "sPaginationType": "full_numbers", // show page numbers
            "bRetrieve"  : true,
            "bProcessing": true,
            "bServerSide": true,
            "sDom": '<""flT>rt<"F"ip>',
            "aoColumns": [{ "sWidth": "100px","bSortable": false }, { "sWidth": "auto" }, { "sWidth": "auto" }],
            "aaSorting":[[1,'asc']],
            "iDisplayLength": 50,
            "sScrollY": calcDataTableHeight() ,
            "bScrollCollapse": true,
            "bSortClasses": false,
            "sAjaxSource": '<?php echo $this->url(array( 'controller'=>'stylefile', 'action'=>'degreegrid'))?>',

            "fnServerParams": function ( aoData ) {
                var filters = getAdvancedFilters();
                aoData.push( { "name": "filters", "value": JSON.stringify(filters.filters) } );
            } ,

            "sServerMethod": "POST",
            "bDestroy": true,

            "oTableTools": {
                "sSwfPath": "<?php echo $this->baseUrl()?>/backend/js/plugins/tables/TableTools/media/swf/copy_csv_xls_pdf.swf"
            },

            "oTableTools": {
                "aButtons": []
            },

            "fnCreatedRow": function( nRow, aData, iDataIndex ) {
                var editar = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Edit" href="#"><img alt="" src="/backend/images/icons/color/pencil.png"></a>');
                var borrar = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Restore" href="#"><img alt="" src="/backend/images/icons/color/arrow-circle-double.png"></a>');
                var view = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="View" href="#"><img alt="" src="/backend/images/icons/control/16/search.png"></a>');

                editar.on('click',function(){
                    var form = $('<form>').attr({
                        name:'editform',
                        method: 'post',
                        action: '<?php echo $this->url(array('module'=>'admin','controller'=>'stylefile', 'action'=>'editstylefile'))?>'
                    });
                    $('<input>').attr({
                        type: 'hidden',
                        id: 'id',
                        name: 'id',
                        value: aData[0]
                    }).appendTo(form);
                    form.appendTo($('body'));
                    form.submit();
                    return false;
                });
                borrar.on('click',function(){
                    $.msgbox("Are you sure you want to restore this Style File? <br> You cannot undo this action", {
                        type: "confirm",
                        buttons : [
                            {type: "submit", value: "Yes"},
                            {type: "cancel", value: "No"}
                        ]
                    }, function(result) {
                        if(result === 'Yes'){
                            var form = $('<form>').attr({
                                name:'deleteform',
                                method: 'post',
                                action: '<?php echo $this->url(array('module'=>'admin','controller'=>'stylefile', 'action'=>'restore'))?>'
                            });
                            $('<input>').attr({
                                type: 'hidden',
                                id: 'Id',
                                name: 'Id',
                                value: aData[0]

                            }).appendTo(form);
                            form.appendTo($('body'));
                            form.submit();
                            return false;
                        }
                    });
                });


                view.on('click',function(){
                    $.ajax( {
                        url: "<?php echo $this->url(array('module'=>'admin','controller'=>'stylefile', 'action'=>'getchangeslog'))?>",
                        data: {Id: aData[0]},
                        dataType: "json",
                        success: function(datos)
                        {
                            var tabla = $("#tgrid");

                            $.each( datos, function( key, value ) {
                                tabla.append(
                                    "<tr><td class='action'>" + value['action'] +
                                    "</td><td class='action'>" + value['stylefile'] +
                                    "</td><td class='action'>" + value['date'] +
                                    "</td><td class='action'>" + value['usrName'] +
                                    "</td></tr>");

                            });

                            $( "#log-info-box" ).dialog('open');
                            $('.ui-dialog-title').text("History Change")


                        },
                        error: function(request, status, error)
                        {
                            mensaje = request.responseText != '' ? request.responseText : 'Timed out or interrupted session, you may be having problems in the network' ;
                            displayMessage( 'error', mensaje, 'Error', '' );
                        },
                        timeout: 20000,
                        type: "POST"
                    });

                });

                $('td:eq(0)', nRow).empty();
                $('td:eq(0)', nRow).append(editar);
                $('td:eq(0)', nRow).append(borrar);
                $('td:eq(0)', nRow).append(view);
            }
            ,"oLanguage": { "sUrl": "<?php echo $this->baseUrl()?>/backend/js/plugins/tables/en.txt"}
        });

        $(window).resize(function () {
            var oSettings = oTable.fnSettings();
            oSettings.oScroll.sY = calcDataTableHeight();
            oTable.fnDraw();
        });

        // draw the filter if they exists
        drawfbreadcrumbs(getAdvancedFilters());

    } );

    function reloadFilters(){
        oTable.fnReloadAjax( '<?php echo $this->url(array( 'module'=>'admin',  'controller'=>'stylefile', 'action'=>'degreegrid'))?>' );
        drawfbreadcrumbs(getAdvancedFilters());
    }
</script>