<?php
$this->jQuery()->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/datatable.fnReloadAjax.js')
->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/TableTools/media/js/TableTools.js')
->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/TableTools/media/js/ZeroClipboard.js')
->addJavascriptFile( $this->baseUrl() . '/backend/js/plugins/tables/advancedFilter.js')
;
$this->headLink()->appendStylesheet($this->baseUrl().'/backend/js/plugins/tables/TableTools/media/css/TableTools.css')
->appendStylesheet($this->baseUrl().'/backend/js/plugins/tables/TableTools/media/css/TableTools_JUI.css')
;
?>
<style>

.ui-dialog form {
    text-align: left;
}
form.dialog > div.row {
    float: right;
    width: 60%;
    padding-top: 9px;
}
.ui-dialog form label {
    cursor: pointer;
    float: left;
    margin: 9px 0 0 10px;
}
</style>
<div class="topHeader" style="top:0px;">
	<div class="titleArea">
		<div class="wrapper">
			<div class="TopPageTitle">
				<div class="bc">
					<ul id="breadcrumbs" class="breadcrumbs">
						<li><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'index', 'action'=>'index') )?>">Home</a></li>						
						<li class="current"><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'blc', 'action'=>'index') )?>">Broken Links</a></li>
					</ul>
				</div>	
			</div>
		</div>
	</div>
</div>
<div id="content">
	<div class="wrapper">
	 	<div id="mensajes"></div>
	 	
		<div class="filterDetailed" id="f1" style="display:none;">
                    <div class="filterContent">
                        <div class="advancedFilterButons">
                        	<a class="button basic" title="" href="javascript:reloadFilters();" id="reload-table">
								<img class="icon" alt="" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/refresh2.png">
								<span title="Reload Filters">Reload</span>
							</a>
                        	<a class="button basic"  title="" href="javascript:clarFilters();" id="clean-filters">
								<img class="icon" alt="" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/smallBrush.png">
								<span title="Clean filters">Clean</span>
							</a>		                            
                        </div>
                        <span class="line"></span>
                        <div class="advancedFilterToggle">
							<div class="toggle acc">
							
			                    <div class="title"><img src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/list.png" alt="" class="titleIcon" /><h6>Title</h6></div>
			                    <div class="menu_body">
			                    	<form class="form" action="" id="" onsubmit="return false;">
			                    		<input type="hidden" name="type" value="TEXT" >
			                    		<input type="hidden" name="op" value="LIKE" >
			                    		<input type="hidden" name="label" value="Title" >
			                    		<div class="formRow">
											<label for="ocwTitle">Title:</label>
											<div class="formRight">
												<input id="ocwTitle" name="ocwTitle" type="text" value="" >
											</div>
											<div class="clear"></div>
										</div>
									</form>	
			                    </div>							
							
			                    <div class="title"><img src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/list.png" alt="" class="titleIcon" /><h6>Field</h6></div>
			                    <div class="menu_body">
			                    	<form class="form" action="" id="" onsubmit="return false;">
			                    		<input type="hidden" name="type" value="TEXT" >
			                    		<input type="hidden" name="op" value="LIKE" >
			                    		<input type="hidden" name="label" value="Field" >
			                    		<div class="formRow">
											<label for="field">Field:</label>
											<div class="formRight">
												<input id="field" name="field" type="text" value="" >
											</div>
											<div class="clear"></div>
										</div>
									</form>	
			                    </div>	
			                    						
	                    		<div class="title"><img src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/list.png" alt="" class="titleIcon" /><h6>Link</h6></div>
			                    <div class="menu_body">
			                    	<form class="form" action="" id="" onsubmit="return false;">
			                    		<input type="hidden" name="type" value="TEXT" >
			                    		<input type="hidden" name="op" value="LIKE" >
			                    		<input type="hidden" name="label" value="Link" >
			                    		<div class="formRow">
											<label for="link">Link:</label>
											<div class="formRight">
												<input id="link" name="link" type="text" value="" >
											</div>
											<div class="clear"></div>
										</div>
									</form>	
			                    </div>
			                </div>
                        </div>
                 </div>
        </div>	 	
	 	
	    <div class="dataTables_wrapper">
	        <!-- Dynamic table -->
	        <div class="widget">
	            <div class="title">
		            <a href="javascript:displayFilter()">
		            	<img style="margin-left: 243px;border:none;" class="titleIcon" alt="" src="<?php echo $this->baseUrl()?>/backend/images/icons/dark/filter.png">
		            </a>
				 	<div id="breadcrumbs-wrapper" style="" >
				       <div class="fbc">
				            <ul id="fbreadcrumbs" class="fbreadcrumbs">
				            </ul>
				            <div class="clear"></div>    
				        </div> 
				    </div>
	            	<div class="clear"></div>
	            </div>                          
	            <table class="display dTable">
	                <thead>
	                    <tr>
							<th>Functions</th>
							<th>Name</th>
							<th>Field</th>
							<th>Link</th>
	                    </tr>
	                </thead>
	                <tbody>	                    
	                </tbody>
	            </table>
	        </div>  
	    </div>
    </div>
</div>
<script type="text/javascript">
    var oTable;
    $(document).ready(function() {


    	var calcDataTableHeight = function() {
            return $(window).height()-300 ; 
            // la altura de la tabla se calcula en base 
        };
    	oTable = $('.dTable').dataTable( { 
            "bJQueryUI": true, // soporte para temas UI
            "sPaginationType": "full_numbers", // muestra los numeros de las paginas
            "bRetrieve"  : true,
            "bProcessing": true,
        	"bServerSide": true, // no hace falta ya que no voy a paginar via servidor
        	"sDom": '<""flT>rt<"F"ip>',
    		"aoColumns": [{ "sWidth": "150px", "bSortable": false }, { "sWidth": "350px" }, { "sWidth": "350px" }, { "sWidth": "750px" }],
    		"aaSorting":[[1,'asc']], 
        	"iDisplayLength": 50,           
            "sScrollY": calcDataTableHeight() ,
            "bScrollCollapse": true,
            "sScrollX": "100%",
            "bSortClasses": false, // no muestra las clases de ordenamiento
            //"bDeferRender": true, // similar al smartrendering de DHTMLX
            "sAjaxSource": '<?php echo $this->url(array( 'controller'=>'blc', 'action'=>'blcgrid'))?>',
            "fnServerParams": function ( aoData ) {
                var filters = getAdvancedFilters();
                aoData.push( { "name": "filters", "value": JSON.stringify(filters.filters) } );
            } , 
            "sServerMethod": "POST",
            "bDestroy": true,
            "oTableTools": {
                "sSwfPath": "<?php echo $this->baseUrl()?>/backend/js/plugins/tables/TableTools/media/swf/copy_csv_xls_pdf.swf"
            },
            "oTableTools": { "aButtons": [ ] },
            "fnCreatedRow": function( nRow, aData, iDataIndex ) {
                // botones
               //	var editar = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Edit" href="#"><img alt="" src="/backend/images/icons/color/pencil.png"></a>');
                var borrar = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Delete" href="#"><img alt="" src="/backend/images/icons/color/cross.png"></a>');
                     borrar.on('click',function(){
                    		$.msgbox("Are you sure you want to remove? <br> You cannot undo this action", {
                    			  type: "confirm",
                    			  buttons : [
                    			    {type: "submit", value: "Yes"},
                    			    {type: "cancel", value: "No"}
                    			  ]
                    			}, function(result) {
                    				if(result === 'Yes'){
                                      	 var form = $('<form>').attr({
                                             name:'deleteform', 
                                             method: 'post', 
                                             action: '<?php echo $this->url(array('module'=>'admin','controller'=>'blc', 'action'=>'delete'))?>'
                                         });
                                         $('<input>').attr({
                                             type: 'hidden',
                                             id: 'Id',
                                             name: 'Id',
                                             value: $(nRow).attr('id')
                                         }).appendTo(form);
                                         form.appendTo($('body'));
                                         form.submit();
                                         return false;
                    				}
                    			});
                     });    
                 	var view = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Edit OCW" href="#"><img alt="" src="/backend/images/icons/control/16/edit.png"></a>');    
	                 view.on('click',function(){
	                	 var form = $('<form>').attr({
	                          name:'editform', 
	                          method: 'post', 
	                          action: '<?php echo $this->url(array('module'=>'admin','controller'=>'ocw', 'action'=>'edit'))?>'
	                      });
	                      $('<input>').attr({
	                           type: 'hidden',
	                           id: 'id',
	                           name: 'id',
	                           value: aData[0]
	                       }).appendTo(form);
	                       form.appendTo($('body'));
	                       form.submit();
                         return false;
	              	 }); 
	                 var gotolink = $('<a class="smallButton" style="line-height: 0px; margin-left:5px" title="Goto '+ aData[3] +'" target="_blank" href="'+ aData[3] +'"><img alt="" src="/backend/images/icons/control/16/world.png"></a>');
                     $('td:eq(0)', nRow).empty();
                     $('td:eq(0)', nRow).append(view);
                     $('td:eq(0)', nRow).append(gotolink);  
                     $('td:eq(0)', nRow).append(borrar);   
                    // console.debug(aData);

	                                      
              }
            ,"oLanguage": { "sUrl": "<?php echo $this->baseUrl()?>/backend/js/plugins/tables/en.txt"}
        });
        

       $(window).resize(function () {
	        var oSettings = oTable.fnSettings();
	        oSettings.oScroll.sY = calcDataTableHeight(); 
	        oTable.fnDraw();
        }); 
		// dibujar los filtros si los hubiese
		drawfbreadcrumbs(getAdvancedFilters()); 

    } );

    function reloadFilters(){
		oTable.fnReloadAjax( '<?php echo $this->url(array( 'module'=>'admin',  'controller'=>'blc', 'action'=>'blcgrid'))?>' );
		drawfbreadcrumbs(getAdvancedFilters()); 
	}
</script>