<?php
$this->headLink()->appendStylesheet($this->baseUrl().'/backend/css/custom/controlB.css');
?>
<style>
    .widget { background: none; border: 0px; clear: both; margin-top: 10px;}
</style>
<div class="titleArea">
    <div class="wrapper">
        <div class="TopPageTitle">
            <div class="bc">
                <ul id="breadcrumbs" class="breadcrumbs">
                    <li><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'index', 'action'=>'index') )?>">Home</a></li>
                    <li class="current"><a href="<?php echo $this->url( array( 'module'=>'admin', 'controller'=>'frontend', 'action'=>'index') )?>">Frontend Dashboard</a></li>
                </ul>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="wrapper" >

    <div class="widget">
        <div class="controlB">
            <ul>
                <li>
                    <a title="Sections Text" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'fsectiontext', 'action'=>'index'))?>" >
                        <img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/sectiontext.png">
                        <span>Sections Texts</span>
                    </a>
                </li>
                <li>
                    <a title="Footer & Social Networks" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'ffooter', 'action'=>'index'))?>" >
                        <img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/header_and_footer.png">
                        <span>Pages Design</span>
                    </a>
                </li>
                <li>
                    <a title="Contact us" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'fcontactus', 'action'=>'index'))?>" >
                        <img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/contact_us_fe.png">
                        <span>Contact us</span>
                    </a>
                </li>
                <li>
                    <a title="Home" href="<?php echo $this->url(array( 'module'=>'admin', 'controller'=>'fhome', 'action'=>'index'))?>" >
                        <img style="width:70px;" alt="" src="<?php echo $this->baseUrl()?>/backend/images/home.png">
                        <span>Home</span>
                    </a>
                </li>
            </ul>
            <div class="clear"></div>
        </div>
    </div>
</div>